# Generated by Django 3.0.8 on 2020-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
